// This file was automatically created by texatlas!
#define TEXATLASNUMBER_LARGE_BRICKS01 0
#define TEXATLASNUMBER_SAND01 1
#define TEXATLASNUMBER_GRASS01 2
#define TEXATLASNUMBER_ROCK01 3
#define TEXATLASNUMBER_ASPHALT01 4
#define TEXATLASNUMBER_BUNKER_WALLS01 5
